spring:
  application:
    name: solva_assignment
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          jdbc:
            time_zone: UTC+6
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format-sql: true
      show-sql: true
alphavantage:
  key: ${ALPHAVANTAGE}